name: pingmetech
favicon: null
layout_spectrum: 0.22467233706265688
typography_spectrum: 0.8650899729691446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9521411960013211
  lightness: 0.5419974797405303
  saturation: 0.6825863616541028
  rhythmicContrast: 0.5814835573546588
purpose: []
