name: pingmetech
favicon: null
layout_spectrum: 0.12307
typography_spectrum: 0.44797
title: PingMe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121f23'
    - '#2a393c'
    - '#435255'
    - '#5e6b6a'
    - '#a4a495'
  brandStrength: 0.9521411960013211
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.5814835573546588
purpose: []
